# Generated by Django 3.2.23 on 2024-04-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('LEARNERSHIP', 'LEARNERSHIP'), ('DIPLOMA', 'DIPLOMA'), ('DEGREE', 'DEGREE'), ('HONOURS', 'HONOURS'), ('MASTERS', 'MASTERS'), ('PHD', 'PHD')], max_length=25, null=True),
        ),
    ]
